### PR TITLE
add python3 support

### PR DESCRIPTION
**Pull request by abchk1234**
Have checked it on my system and MX 18.3. Recommend you to test it too!

### CODE REVIEW

**Comment by AdrianTM** [comment]
Thanks for the contributions. I think in MX-19 we'll end up using mx-datetime https://github.com/mx-linux/mx-datetime instead of this tool so please don't spend too much time on this one.

**Comment by abchk1234** [comment]
Oh, ok, thanks for the info @AdrianTM !

**Comment by abchk1234** [comment]
@AdrianTM please check https://github.com/MX-Linux/mx-timeset/pull/1 for merge in https://github.com/mx-linux/mx-datetime as it fixes bug with timezone.

**Comment by abchk1234** [comment]
> @AdrianTM please check #1 for merge in https://github.com/mx-linux/mx-datetime as it fixes bug with timezone.

The bug is likely not present in mx-datetime as it is setting the time via a different way.

For viewing both gave same output when I checked. Opened https://github.com/MX-Linux/mx-datetime/pull/4 .

**Pull request merged**
